<?php
  function random_article_menu() {
    $items['random_article'] = array(
      'title' => 'Surprise Me',
      'page callback' => 'random_article_page',
      'access callback' => 'user_access',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
    );
    $items['pick_random'] = array(
        'title' => 'Random Article Picker',
        'type' => MENU_CALLBACK,
        'page callback' => 'get_random_article',
        'access arguments' => array('access content'),
    );
    return $items;
  }

  function random_article_page() {
      return array(
          '#type' => 'link',
          '#title' => t('Ajax Link'),
          '#href' => 'pick_random',
          '#prefix' => '<div id="ajax-link">',
          '#suffix' => '</div><div id="ajax-display"></div>',
          '#ajax' => array(
              'effect' => 'fade',
          )
      );
  }

  function get_random_article($type = 'ajax', $nid = 0) {
    $result = db_query("SELECT nid FROM node WHERE type = 'article' ORDER BY RAND() LIMIT 1");

    foreach ($result as $record) {
          $nid = $record->nid;
    }

    $output = random_article_load_node($nid);
    if ($type == 'ajax') {
      $commands = array();
      $commands[] = ajax_command_replace('#content', '<div id="content">' . $output . '</div>');
      $page = array(
        '#type' => 'ajax',
        '#commands' => $commands
      );
      ajax_deliver($page);
    }
    elseif ($nid > 0) {
      drupal_goto('node/' . $nid);
    }
    else {
      $output = '<div id="content">' . $output . '</div>';
      return $output;
    }
  }


  function random_article_load_node($nid = 0) {
    $node = node_load($nid, NULL, false);
    if ($node) {
      $vnode = node_view($node);
      return theme("node", $vnode);
    }
  }
